export { default as Home } from './HomePage';
export { default as Products } from './ProductsPage';
export { default as ProductDetail } from './ProductDetailsPage';
export { default as Cart } from './CartPage';
export { default as Checkout } from './CheckoutPage';
export { default as Register } from './RegisterPage';
export { default as OrderCompletion } from './OrderCompletionPage';
export { default as OrderHistory } from './OrderHistory';
export { default as UserDetails } from './UserDetailsPage';